---
- hosts: all
  gather_facts: yes
  remote_user: root
  roles:
    - conf-dns
    - { role: common-apt, when: ansible_os_family == 'Debian' }
    - { role: common-yum, when: ansible_os_family == 'RedHat' }
    - { role: disable-selinux, when: ansible_os_family == 'RedHat' }
    - conf-ntp
    - postfix-client
