---
- src: git+https://github.com/osu-itis/ansible-common-apt
  name: common-apt

- src: git+https://github.com/osu-itis/ansible-common-yum
  name: common-yum

- src: git+https://github.com/osu-itis/ansible-postfix-client
  name: postfix-client

- src: git+https://github.com/osu-itis/ansible-conf-dns
  name: conf-dns

- src: git+https://github.com/osu-itis/ansible-conf-ntp
  name: conf-ntp

- src: git+https://github.com/osu-itis/ansible-disable-selinux
  name: disable-selinux

- src: git+https://github.com/osu-itis/ansible-epel-repository
  name: epel-repository
